spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/divide_experience?currentSchema=article_service
    username: postgres
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    url: jdbc:postgresql://localhost:5432/divide_experience
    user: postgres
    password: ${DB_PASS}
    default-schema: article_service
    drop-first: false

security:
  oauth2:
    web:
      jwt:
        key-value: ${JWT_WEB_KEY}
    article:
      jwt:
        key-value: ${JWT_ARTICLE_KEY}

article_service:
  static_source:
    base_path: /home/anton/projects/divide_experience/static/%s/%s/%s