server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        native:
          search-locations: classpath:/shared

---
eureka:
  instance:
    preferIpAddress: true
    ip-address: ${ENV_DOCKER_HOST_IP}
    nonSecurePort: ${ENV_DOCKER_HOST_PORT}
    instance-id: ${ENV_DOCKER_HOST_IP}:${spring.application.name}:${ENV_DOCKER_HOST_PORT}
    hostname: ${ENV_DOCKER_HOST_IP}
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: ${ENV_EUREKA_DEFAULT_ZONE}

#eureka:
#  instance:
#    ip-address: localhost
#    nonSecurePort: ${server.port}
#    instance-id: localhost:${spring.application.name}:${server.port}
#    preferIpAddress: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/