spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/article
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false


server:
  servlet:
    context-path: /article
  port: 6002

