server:
  port: 8001

spring:
  application:
    name: gatewayService
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 10000
  connection-timeout: 10000

zuul:
  host:
    socket-timeout-millis: 100000
  sensitiveHeaders: Cookie,Set-Cookie
  include-debug-header: true
  routes:
    article:
      service-id: articleService
      path: /article/**
      url: http://localhost:6002/article/
    oauth:
      service-id: authService
      path: /auth/**
      stripPrefix: false
      url: http://localhost:7002/

