config_role:
  java_tool_options: "-Xms256m -Xmx256m"
  folder: /home/projects/divide_experience_project/container_folder/div_config_service
  host_port: 8888
  container_port: 8888
  path_to_docker_file: services/config-service