---
- name: Creates directories
  file: path="{{item}}" state=directory owner="root" group="root" mode="775"
  with_items:
    - "{{ gateway_role.folder }}/data"
    - "{{ gateway_role.folder }}/files"
    - "{{ gateway_role.folder }}/logs"
  tags:
    - deploy_gateway_service

- name:  Docker registry login
  become: true
  docker_login:
    username: "{{ docker.username }}"
    password: "{{ docker.password }}"
  tags:
    - deploy_gateway_service

- name: Docker stops and rm div_gateway_service
  docker_container:
    name: div_gateway_service
    state: absent
  tags:
    - deploy_gateway_service

- name: Build jar file (Just for local usage)
  shell:
    chdir: "{{ source_folder }}/{{ gateway_role.path_to_docker_file }}"
    cmd: mvn clean package
  tags:
    - create_gateway_service_image

- name: Remove image div_config_service  (Just for local usage)
  docker_image:
    state: absent
    name: "{{ docker.registry_path }}"
    tag: div_gateway_service_latest
    force: "yes"
  tags:
    - delete_gateway_service_image
    - create_gateway_service_image

- name: Create a new image (Just for local usage)
  docker_image:
    path: "{{ source_folder }}/{{ gateway_role.path_to_docker_file }}"
    name: "{{ docker.registry_path }}"
    tag: div_gateway_service_latest
    push: "yes"
    nocache: "yes"
  tags:
    - create_gateway_service_image

- name: Docker starts div_gateway_service
  docker_container:
    name: div_gateway_service
    image: "{{ docker.registry_path }}:{{ gateway_service_version }}"
    pull: "yes"
    restart_policy: "always"
    ports:
        - "{{ gateway_role.host_port }}:{{ gateway_role.container_port }}"
    volumes:
      - "{{ gateway_role.folder }}/data:{{ gateway_role.folder }}/data"
      - "{{ gateway_role.folder }}/files:{{ gateway_role.folder }}/files"
      - "{{ gateway_role.folder }}/logs:{{ gateway_role.folder }}/logs"
    env:
      PROFILE: "{{ env }}"
      ENV_DOCKER_HOST_IP: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      ENV_DOCKER_HOST_PORT: "{{ gateway_role.host_port }}"
      ENV_EUREKA_DEFAULT_ZONE: "{{ ENV_EUREKA_DEFAULT_ZONE }}"
      JAVA_TOOL_OPTIONS: "{{ gateway_role.java_tool_options }}"
      ENV_WEB_URLS: "{{ ENTERED_WEB_URLS | default(ENV_WEB_URLS) }}"
      encrypt.key: "{{ secret_key }}"
    state: started
  tags:
    - deploy_gateway_service
