---
gateway_role:
  java_tool_options: "-Xms256m -Xmx256m"
  folder: /home/projects/divide_experience_project/container_folder/div_gateway_service
  host_port: 80
  container_port: 6003
  path_to_docker_file: services/gateway-service