---
registry_role:
  java_tool_options: "-Xms100m -Xmx200m"
  folder: /home/projects/divide_experience_project/container_folder/div_registry_service
  host_port: 8000
  container_port: 8000
  path_to_docker_file: services/registry-service