spring:
  application:
    name: authService
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/divide_experience?currentSchema=auth_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: test, prod